const mongoose=require("mongoose")
const cartSchema=new mongoose.Schema({
  user:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User",
    required:true
  },
  cartItems:[{
    product:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"Product",
      required:true
    },
    size:{
      type:String,
      required:true
    },
    ingridients:[
      {
        text:{type:String},
        price:{type:Number}
      }
    ],
    ingridientsTotal:{
      type:Number,
      default:0,
      required:true
    },
    quantity:{
      type:Number,
      default:1,
      required:true
    },
    price:{
      type:Number,
      required:true
    },
    total:{
      type:Number,
      required:true
    }
  }]
})
const Cart=mongoose.model("Cart",cartSchema)
module.exports=Cart
